name: Archive Detail
on:
  workflow_dispatch:
    inputs:
      envs:
        description: "env"
        required: false
        default: ""
  repository_dispatch:
    types: [archive-detail]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    concurrency: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: npm i npm -g
      - run: npm version
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install
        run: "npm i"
      - name: Build Archive
        run: ${{ github.event.inputs.envs }} npm run archive:detail
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "chore: archive files"
          branch: archive
          delete-branch: true
          title: "chore: archive files"
