name: Auto merge
on:
  workflow_dispatch:
  pull_request_target:
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        if: (github.actor=='theowenyoung' || github.actor=='imprivate') && (github.head_ref=='update-dependencies' || github.head_ref=='archive')
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 30
          token: ${{ secrets.PERSONAL_TOKEN }}
